
[build]
  builder = "gcr.io/paketo-buildpacks/builder:tiny"

[[services]]
  internal_port = 54321
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 2500
    soft_limit = 2000

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000