# fly.toml file generated for  on 2020-07-01T21:55:26+05:30

app = "grpc-test"

[build]
  builder = "cloudfoundry/cnb:tiny"

[[services]]
  internal_port = 54321
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000